# compiler
CC=g++ -std=c++11

# compiler options (-g: turn on debugging; -Wall: turn on warnings -Werror: warning like errors)
CPPFLAGS=-g -Wall -Werror
	
all: replace_spaces.o 
	$(CC) -o replace_spaces  replace_spaces.o $(CPPFLAGS)
