# compiler
CC=g++ -std=c++11

# compiler options (-g: turn on debugging; -Wall: turn on warnings -Werror: warning like errors)
CPPFLAGS=-g -Wall -Werror
	
all: telephone_words.o 
	$(CC) -o telephone_words telephone_words.o $(CPPFLAGS)
