# compiler
CC=g++ -std=c++11

# compiler options (-g: turn on debugging; -Wall: turn on warnings -Werror: warning like errors)
CPPFLAGS=-g -Wall -Werror
	
all: set_of_stacks.o 
	$(CC) -o set_of_stacks set_of_stacks.o $(CPPFLAGS)
