# compiler
CC=g++ -std=c++11

# compiler options (-g: turn on debugging; -Wall: turn on warnings -Werror: warning like errors)
CPPFLAGS=-g -Wall -Werror
	
all: rotated_array_search.o 
	$(CC) -o rotated_array_search rotated_array_search.o $(CPPFLAGS)
